// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmMSb3odosWrmBAfLdVW1_iAhRqC2PiwM',
    appId: '1:1038744556460:web:bbb9f44aee4c6e564aa009',
    messagingSenderId: '1038744556460',
    projectId: 'zentry-f40a0',
    authDomain: 'zentry-f40a0.firebaseapp.com',
    storageBucket: 'zentry-f40a0.firebasestorage.app',
    measurementId: 'G-D2MRLR6KWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtxxyN1gQdOvSs7zPR08tGRYsfOxbHh-E',
    appId: '1:1038744556460:android:e41f568e504739dc4aa009',
    messagingSenderId: '1038744556460',
    projectId: 'zentry-f40a0',
    storageBucket: 'zentry-f40a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxxZ0ZM1tvyU4WcUTMUfdUc8h9j4wkvWw',
    appId: '1:1038744556460:ios:dfc1220ed4c6e0284aa009',
    messagingSenderId: '1038744556460',
    projectId: 'zentry-f40a0',
    storageBucket: 'zentry-f40a0.firebasestorage.app',
    iosClientId: '1038744556460-lm9d4l2aqo31ojurpd4nq5hmtef2gh9m.apps.googleusercontent.com',
    iosBundleId: 'com.example.zentry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxxZ0ZM1tvyU4WcUTMUfdUc8h9j4wkvWw',
    appId: '1:1038744556460:ios:dfc1220ed4c6e0284aa009',
    messagingSenderId: '1038744556460',
    projectId: 'zentry-f40a0',
    storageBucket: 'zentry-f40a0.firebasestorage.app',
    iosClientId: '1038744556460-lm9d4l2aqo31ojurpd4nq5hmtef2gh9m.apps.googleusercontent.com',
    iosBundleId: 'com.example.zentry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmMSb3odosWrmBAfLdVW1_iAhRqC2PiwM',
    appId: '1:1038744556460:web:2afe602b983cdb6a4aa009',
    messagingSenderId: '1038744556460',
    projectId: 'zentry-f40a0',
    authDomain: 'zentry-f40a0.firebaseapp.com',
    storageBucket: 'zentry-f40a0.firebasestorage.app',
    measurementId: 'G-ZGK2QN3KLY',
  );
}
